"""Add Comment.is_deleted column and set all is_deleted=False.

Revision ID: fb0496e0c29d
Revises: None
Create Date: 2016-04-13 00:20:06.205521

"""

# revision identifiers, used by Alembic.
revision = 'fb0496e0c29d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    op.execute("UPDATE comment SET is_deleted=0")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_deleted')
    ### end Alembic commands ###
